import { readData, writeData } from './_lib/blob-db.js';

const SEED_DATA = [
  {"id":"187b622e-bdf9-4a63-b26d-118309af46b6","title":"Limputra HR — Human Resources Management System For Limputra Group","description":"Modern, HR and Payroll platform untuk Limputra Group yang dirancang untuk mengelola seluruh siklus sumber daya manusia — mulai dari rekrutmen, absensi, cuti, penilaian kinerja, hingga penggajian","image":"","link":"","linkType":"github","demoUrl":"http://103.155.250.26:8001","features":"<p>Limputra HR adalah aplikasi Human Resources Management System (HRMS) lengkap yang dikembangkan untuk memenuhi kebutuhan operasional HR PT Uninet. Sistem ini mencakup dua modul utama:</p><p>Modul HR Manajemen karyawan, absensi, cuti, rekrutmen, kinerja, pelatihan</p><p>Payroll Penggajian, pajak, tunjangan, bonus, pesangon (gratuity)</p><h3>Visi</h3><p>Memberikan pengalaman HR digital yang mobile-first, real-time, dan terintegrasi — dari absensi di lapangan hingga slip gaji di genggaman tangan karyawan.</p><h2>Highlight Fitur</h2><h3><strong>Multi-level Approval (SPV → Mgr → HR)</strong></h3><p>Alur persetujuan berjenjang yang dapat dikonfigurasi per departement.</p><h3>Check-in dengan Foto &amp; GPS</h3><p>Verifikasi kehadiran berbasis lokasi dan foto selfie.</p><h3>Face Recognition (FaceNet512)</h3><p>Validasi wajah untuk perubahan foto profil &amp; akses.</p><h3>Fingerprint Clock in / out</h3><p>Integrasi absensi melalui mesin finger.</p><h3>Push Notification (OneSignal + In-App)</h3><p>Pemberitahuan real-time untuk approval &amp; reminder.</p><h3>Shift &amp; Roster Management</h3><p>Kalender shift bulanan dengan filter multi-dimensi.</p><h3>Payroll</h3><p>Dukungan perhitungan pajak &amp; pesangon sesuai regulasi lokal</p>","createdAt":"2026-07-20T14:47:53.184Z","updatedAt":"2026-07-20T17:13:47.725Z"},
  {"id":"9e510471-a43f-49e1-ba6e-d054ff501151","title":"MettaDC - Data Center Customer Portal","description":"Portal manajemen data center terintegrasi untuk PT Metta Data Center, menyediakan Admin Panel dan Customer Portal dalam satu platform.","image":"","link":"https://github.com/fajarizaf/portalmetta","linkType":"github","demoUrl":"http://202.145.0.38:3011","features":"<h2>Fitur Utama</h2><h3>1. Configurable Document Engine (ERP)</h3><p>Sistem manajemen dokumen dinamis yang dapat dikonfigurasi sepenuhnya melalui UI Admin. Mendukung berbagai jenis dokumen bisnis tanpa perubahan kode.</p><h3>2. Sales &amp; Order Management</h3><ul><li>Direct Order: Customer langsung memesan produk tertentu</li><li>Request Order: Customer mengajukan permintaan, menunggu approval admin</li><li>Multi-Item Order: Pemesanan beberapa item sekaligus</li><li>Auto SO: Quotation yang di-approve otomatis membuat Sales Order</li><li>Auto Subscription: SO yang di-approve otomatis membuat Subscription aktif</li></ul><h3>3. Billing &amp; Subscription Management</h3><ul><li>Prorate calculation (harian) untuk bulan pertama/tidak genap</li><li>Billing cycle: Monthly, Quarterly, Annually</li><li>Setup fee (one-time charge) untuk instalasi</li><li>Bulk invoice generation untuk semua subscription aktif</li><li>Invoice PDF via Puppeteer</li><li>Email delivery otomatis ke customer</li><li>Currency formatting Rupiah (IDR)</li></ul><h3>4. Product Management</h3><ul><li>Hierarchical product groups (parent-child)</li><li>Pricing models: Fixed, Discount, Tiered</li><li>Dynamic specification fields per produk</li><li>Order mode: Direct atau Request</li></ul><h3>5. Inventory &amp; Goods Management</h3><ul><li>Stock tracking per branch per produk</li><li>Goods In/Out dengan approval workflow</li><li>Audit trail lengkap (IN/OUT/ADJUSTMENT)</li><li>Real-time stock balance calculation</li></ul><h3>6. Data Center Infrastructure Management</h3><p>Manajemen infrastruktur data center termasuk rack, server, dan monitoring.</p>","createdAt":"2026-07-20T15:14:57.145Z","updatedAt":"2026-07-20T16:15:56.969Z"},
  {"id":"377e07e8-c512-412a-a9db-5781e8e152af","title":"Dashboard Uninet","description":"DashUninet adalah portal back-office CRM/ERP terintegrasi untuk pengelolaan layanan internet PT. Uninet Media Sakti. Aplikasi ini mengelola siklus hidup pelanggan lengkap mulai dari leads penjualan, order, aktivasi langganan (otomatis via Mikrotik RouterOS), penagihan invoice, hingga support ticket.","image":"","link":"https://github.com/fajarizaf/dashuninet","linkType":"github","demoUrl":"https://staging.uninet.net.id/login","features":"<h2>Fitur Utama</h2><h3>Dashboard</h3><p>Dashboard Utama: Ringkasan performa bisnis secara real-time, Revenue Analisis pendapatan per periode, Subscription Statistik langganan aktif/nonaktif, Sales Order Performa penjualan &amp; progress order</p><h3>Modul Penjualan</h3><p>Pipeline Manajemen leads &amp; prospek penjualan, Pembuatan Sales Order approve progress tracking order, SPK / BA Surat Perintah Kerja &amp; Berita Acara digital, Komisi Tracking Komisi sales per order</p><h3>Modul Layanan</h3><p>Subscription Aktivasi update suspensi deaktivasi langganan, Mikrotik Router Manajemen perangkat jaringan &amp; PPPoE secrets, Auto Job Auto activate/suspend/deactivate via queue jobs</p><h3>Modul Keuangan</h3><p>Invoice Draft publish batch publish reminder, Pembayaran Upload bukti bayar approval payment tracking, Deposit Topup approval auto-deduct balance, Promo Kode promosi &amp; diskon</p><h3>Modul Pelanggan</h3><p>Customer Data pelanggan aktif korporat membership, Downline Sistem referral &amp; jaringan pelanggan, Credit Point Poin loyalitas &amp; reward redemption, Loyalty Katalog reward &amp; pengelolaan hadiah</p><h3>Modul Support</h3><p>Ticket Layanan pelanggan (open/close/overdue), Documentation CMS dokumentasi &amp; panduan pengguna</p><h3>Modul Lainnya</h3><p>Product Katalog produk harga billing cycle, Reseller Manajemen mitra/reseller, Site project &amp; area cakupan, Banner Manajemen, Laporan ke Excel (Customer Subscription Invoice)</p>","createdAt":"2026-07-20T10:35:09.366Z","updatedAt":"2026-07-20T16:23:08.640Z"},
  {"id":"41c7843b-0e79-4a88-a702-3ecbf23fb2e7","title":"Peta Sebaran Unras","description":"Aplikasi monitoring dan visualisasi data unjuk rasa (demonstrasi) di seluruh provinsi Indonesia. Aplikasi ini menyediakan peta interaktif, dashboard statistik, dan panel admin untuk mengelola data aksi massa.","image":"","link":"https://github.com/fajarizaf/aksi-demo","linkType":"github","demoUrl":"http://103.153.42.77:5174/","features":"<h2>Fitur Utama</h2><ul><li>Peta Interaktif - Peta Indonesia berbasis Leaflet.js dengan penanda berwarna berdasarkan status aksi (Rencana/Berlangsung/Selesai)</li><li>Clustering Marker - Pengelompokan otomatis marker pada provinsi dengan banyak aksi</li><li>Panel Admin - CRUD data aksi, impor Excel/CSV, input manual</li><li>Dashboard Grafik - Visualisasi nilai tukar USD/IDR, harga BBM, dan harga bahan pokok</li><li>Autentikasi - Sistem login admin berbasis session cookie</li><li>Deduplikasi Data - Pencocokan otomatis saat impor untuk menghindari data ganda</li></ul>","createdAt":"2026-07-20T15:42:13.837Z","updatedAt":"2026-07-20T17:24:48.595Z"},
  {"id":"1","title":"WHMCS Addons - ShopeePay","description":"ShopeePay payment gateway module integrated with WHMCS.","image":"","link":"https://github.com/fajarizaf/picovid","linkType":"github","demoUrl":"","features":"<h3>Fitur Utama :</h3><ul><li>Real-time COVID-19 data tracking</li><li>Interactive charts and statistics</li><li>Province-level data breakdown</li><li>Cross-platform (iOS &amp; Android)</li></ul>","createdAt":"2024-01-01T00:00:00.000Z","updatedAt":"2026-07-20T16:56:44.105Z"},
  {"id":"2","title":"WHMCS Addons - Bulk Services","description":"Hosting bulk services module integrated with WHMCS internal API.","image":"","link":"https://github.com/fajarizaf/WHMCS-ADDON-BulkServices","linkType":"github","demoUrl":"","features":"<h3>Fitur Utama :</h3><ul><li>Bulk service management via WHMCS API</li><li>Automated provisioning</li><li>CSV import/export support</li></ul>","createdAt":"2024-01-02T00:00:00.000Z","updatedAt":"2026-07-20T16:10:23.353Z"},
  {"id":"4","title":"Certification Issuance System","description":"Internal web application for managing and issuing certifications.","image":"","link":"https://github.com/fajarizaf/app.asttatindo","linkType":"github","demoUrl":"","features":"<h3>Fitur Utama :</h3><ul><li>Certificate generation &amp; print</li><li>Participant data management</li><li>Verification system</li><li>Batch processing support</li></ul>","createdAt":"2024-01-04T00:00:00.000Z","updatedAt":"2026-07-20T17:00:18.327Z"},
  {"id":"5","title":"WHMCS Addons - ShopeePay","description":"ShopeePay payment gateway module integrated with WHMCS.","image":"","link":"https://github.com/fajarizaf/WHMCS-ADDON-ShopeePay","linkType":"github","demoUrl":"","features":"<ul><li>ShopeePay payment integration</li><li>Automatic invoice reconciliation</li><li>Callback handling</li></ul>","createdAt":"2024-01-05T00:00:00.000Z","updatedAt":"2026-07-20T17:03:49.019Z"},
  {"id":"6","title":"WHMCS Addons - Virtual Account","description":"Faspay Virtual Account payment module for WHMCS orders.","image":"","link":"https://github.com/fajarizaf/WHMCS-ADDON-Virtual-Account-Payment","linkType":"github","demoUrl":"","features":"<h3>Fitur Utama :</h3><ul><li>Virtual Account generation</li><li>Multi-bank support</li><li>Real-time payment notification</li></ul>","createdAt":"2024-01-06T00:00:00.000Z","updatedAt":"2026-07-20T17:07:19.921Z"}
];

export default async function handler(req, res) {
  if (req.method !== 'POST') {
    return res.status(405).json({ error: 'Method not allowed' });
  }

  try {
    const { action } = req.query;

    await writeData(SEED_DATA);
    return res.status(200).json({
      message: action === 'reset' ? 'Data berhasil direset' : 'Seed data berhasil',
      count: SEED_DATA.length
    });
  } catch (error) {
    console.error('Seed error:', error);
    return res.status(500).json({ error: 'Gagal melakukan seed data', detail: error.message });
  }
}
